Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [1]:
import numpy as np #import liabraries

In [2]:
a = np.array([7,8,9,4]) #create array/vector

In [3]:
N = 4 # define number of columns in output

In [4]:
np.vander(a,N) # generate vandermonde matrix

array([[343,  49,   7,   1],
       [512,  64,   8,   1],
       [729,  81,   9,   1],
       [ 64,  16,   4,   1]])

In [5]:
##for i in range(N):
    #b = (N-i-1)
    #print(b)
#Out : 3,2,1,0
    

In [6]:
np.column_stack([a**(N-i-1) for i  in range (N)] ) #to convert arrays as columns

array([[343,  49,   7,   1],
       [512,  64,   8,   1],
       [729,  81,   9,   1],
       [ 64,  16,   4,   1]], dtype=int32)

In [7]:
#Optional
np.vander(a,increasing = True)

array([[  1,   7,  49, 343],
       [  1,   8,  64, 512],
       [  1,   9,  81, 729],
       [  1,   4,  16,  64]])

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [18]:
def average_with_window():
    sequence = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
    window = 3
    i = 0
    moving_average=[]
    while i < len(sequence) - window + 1:
        k = sequence[i: i + window]
        seq_average = sum(k)/window
        moving_average.append(seq_average)
        i += 1
print(moving_average)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]


In [23]:
#len(sequence)

13

In [7]:
#len(sequence) - window + 1

11

In [20]:
#k = sequence[i: i + window]
#k

[7, 2, 8]

In [22]:
#seq_average = sum(k)/window
#seq_average

5.666666666666667

In [4]:
#i = 0
#moving_average=[]
#while i < len(sequence) - window + 1:
    #k = sequence[i: i + window]
    #seq_average = sum(k)/window
    #moving_average.append(seq_average)
    #i += 1
#print(moving_average)
    

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
